version: '3'
services:
  redis:
    image: 'redislabs/redismod'
    networks:
      - backend
  web1:
    image: 'pattaraponssky/swarm02-web:1.0'
    hostname: web1
    networks:
      - backend
  web2:
    image: 'pattaraponssky/swarm02-web:1.0'
    hostname: web2
    networks:
      - backend
  nginx:
    image: 'pattaraponssky/swarm02-nginx:1.0'
    depends_on:
    - web1
    - web2
    networks:
      - backend
      - webproxy
    deploy:
        replicas: 1
        labels:
          - traefik.docker.network=webproxy
          - traefik.enable=true
          - traefik.constraint-label=webproxy
          - traefik.http.routers.spcn11swarm02-https.entrypoints=websecure
          - traefik.http.routers.spcn11swarm02-https.rule=Host("spcn11swarm02.xops.ipv9.me")
          - traefik.http.routers.spcn11swarm02-https.tls.certresolver=default
          - traefik.http.services.spcn11swarm02.loadbalancer.server.port=80
          - traefik.http.routers.spcn11swarm02-https.tls=true
        resources:
          reservations:
            cpus: '0.1'
            memory: 10M
          limits:
            cpus: '0.4'
            memory: 250M

networks:
  webproxy:
    external: true
  backend:
    driver: overlay
